### ISSUE TITLE
SGE: Internal Server Error if editing contact and contact page layout has Pardot components

### ISSUE THREAD

**Issue by judisohn** [SalesforceFoundation/gem#207]
* **What is the current behavior?**

Using Single Gift Entry, select 'Edit Contact' button and make any edit to Contact, Save

The data saves to Contact, but SGE page renders error:

`Uncaught Error in $A.getCallback() [Value is not a string, ObjectId, or FieldId.]`

* **What is the expected behavior?**

After saving Contact error, user should be able to continue with Single Gift Entry form.

* **Workaround/Cause**

The issue is with Pardot Visualforce components on the Contact page layout. When those components are removed, the page saves normally. We need to determine where the conflict is in these components.

In the meantime, users should edit Contacts directly on the Contact record and not through Single Gift Entry.

**Comment by judisohn** [comment]
**lurch: add

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CA7nQAG" target="_blank">W-035658</a>

**Comment by judisohn** [comment]
**lurch: detach W-035658

**Comment by LurchTheButler** [comment]
Detached <a href="https://foundation.my.salesforce.com/a2x1E000001CA7nQAG" target="_blank">W-035658</a>

**Comment by judisohn** [comment]
**lurch: attach W-035650

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CA79QAG" target="_blank">W-035650</a>
