### ISSUE TITLE
Make Opportunity Stage required in SGE

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/gem#209]
As a gift entry user I want the Opportunity Stage to be a required field so that I follow standard Salesforce and NPSP behavior and so that I explicitly select the desired Stage.

**Comment by lparrott** [comment]
**lurch: attach W-035552

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C9sdQAC" target="_blank">W-035552</a>
