### ISSUE TITLE
Winter 20: In SGE after entering amount there is an error

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/gem#214]
Steps to duplicate: 
1. Create a scratch org with dev_prerelease 
2. Run trial_org flow. 
3. Go to sge. 
4. Choose a contact, then go to amount and type in a value and then go to next. Get an error: (note- the stage field drop down is empty after this)
This page has an error. You might just need to refresh it. First, would you give us some details? (We're reporting this as error ID: 606699099)
 [NoErrorObjectAvailable] Script error. a()@https://static.lightning.force.com/cs46/auraFW/javascript/PBO944yw5MGHc-5iZ4R1Jw/aura_prod.js:927:85 {anonymous}()@https://static.lightning.force.com/cs46/auraFW/javascript/PBO944yw5MGHc-5iZ4R1Jw/aura_prod.js:927:278 V.dispatchEvent()@https://static.lightning.force.com/cs46/auraFW/javascript/PBO944yw5MGHc-5iZ4R1Jw/aura_prod.js:3:25135 V.handleBlur()@https://momentum-speed-5265-dev-ed.lightning.force.com/components/lightning/input.js:2:30283

**Comment by lparrott** [comment]
**lurch: attach W-035863

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CARJQA4" target="_blank">W-035863</a>
