### ISSUE TITLE
Update to Schedule Date on SGE

### ISSUE THREAD

**Issue by KietTruongSFDO** [SalesforceFoundation/gem#215]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the GEM Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Currently, the Scheduled date is required no matter if the payment is paid or written off. 

* **What is the expected behavior?**
It should be based off of the "Enforce Accounting Data Consistency". 
**If that setting on:**
Payment Date required for Paid Payments (although SGE will auto-fill that value if field is left blank).
Payment Date required for Write Offs.
Scheduled Date required for unpaid scheduled Payments.
**With the setting off:**
Payment Date not required for any kind of Payment.
Scheduled Date not required for any kind of Payment

* **What is the motivation / use case for changing the behavior?**

* **Acceptance Criteria**

  - **Given**: I am on a certain page
  - **When**: I click a button
  - **Then**: An action should occur

* **Keyboard Acceptance Criteria**

  - **Given**: I am navigating the site using only my keyboard
  - **When**: I tab to the button
  - **Then**: I should see the button highlighted on focus
  - **And When**: I press enter on a highlighted button
  - **Then**: An action should occur

* **Screenreader Acceptance Criteria**

  - **Given**: I am using a screenreader to navigate the site
  - **When**: I tab to the button
  - **Then**: I should hear the label of the button
  - **And When**: I press enter
  - **Then**: I should hear that an action has occurred

**Comment by KietTruongSFDO** [comment]
**lurch: attach W-034762

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001C8IYQA0" target="_blank">W-034762</a>
