### ISSUE TITLE
Add 2 New GAU fields to GEM Gift Layout

### ISSUE THREAD

**Issue by lparrott** [SalesforceFoundation/gem#218]
Since NPSP added new objects to their Data Import mapping feature, we should add those fields to our custom "GEM Gift Layout" Page Layout.

**Comment by lparrott** [comment]
**lurch: attach W-036147

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E000001CAwrQAG" target="_blank">W-036147</a>
