### ISSUE TITLE
Payment Allocations are orphaned when deleting Recurring Donations

### ISSUE THREAD

**Issue by KietTruongSFDO** [SalesforceFoundation/gem#224]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the GEM Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Given a Recurring Donation with Payment Allocations, when the Recurring Donation is deleted, the Payment Allocations are not deleted with it. 

* **What is the expected behavior?**
When a Recurring Donation is deleted, the Payment Allocations are also deleted with it. 

* **What is the motivation / use case for changing the behavior?**
There should be no orphaned Payment Allocations when deleting a Recurring Donation. Orphaned Payment Allocations take up unnecessary space and is difficult to maintain. 

* **Acceptance Criteria**

  - **Given**: A Recurring Donation which has Payment Allocations associated with the Opportunity
  - **When**: The Recurring Donation is deleted
  - **Then**:  The Payment Allocations should be deleted as well. 

* **Keyboard Acceptance Criteria**

  - **Given**: I am navigating the site using only my keyboard
  - **When**: I tab to the button
  - **Then**: I should see the button highlighted on focus
  - **And When**: I press enter on a highlighted button
  - **Then**: An action should occur

* **Screenreader Acceptance Criteria**

  - **Given**: I am using a screenreader to navigate the site
  - **When**: I tab to the button
  - **Then**: I should hear the label of the button
  - **And When**: I press enter
  - **Then**: I should hear that an action has occurred

**Comment by KietTruongSFDO** [comment]
**lurch: attach W-033708

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vYVQAY" target="_blank">W-033708</a>
