### ISSUE TITLE
An error is not shown when editing/removing an Opportunity Allocation that is tied to a paid Payment via Manage Allocations

### ISSUE THREAD

**Issue by KietTruongSFDO** [SalesforceFoundation/gem#239]
**Note: FOR INTERNAL USE ONLY. For support questions, please use the GEM Chatter group in [The Power of Us Hub](https://powerofus.force.com).
For feature requests, please use the Ideas tab in [The Power of Us Hub](https://powerofus.force.com).**

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
If the user edits/removes an Opportunity allocation through the Manage Allocation screen and the allocation is tied to a paid Payment and the default GAU is also not used, no error is displayed. 

* **What is the expected behavior?**
There should be an error displayed when editing/removing an Opportunity allocation that is tied to a paid payment and there is no default GAU being used. 

* **What is the motivation / use case for changing the behavior?**

* **Acceptance Criteria**

  - **Given**: An Opportunity with an Opportunity level allocation and associated paid Payment allocations (not using the default GAU)
  - **When**: I edit/remove the Opportunity level allocation
  - **Then**: An error should display, preventing this action from happening. 

* **Keyboard Acceptance Criteria**

  - **Given**: I am navigating the site using only my keyboard
  - **When**: I tab to the button
  - **Then**: I should see the button highlighted on focus
  - **And When**: I press enter on a highlighted button
  - **Then**: An action should occur

* **Screenreader Acceptance Criteria**

  - **Given**: I am using a screenreader to navigate the site
  - **When**: I tab to the button
  - **Then**: I should hear the label of the button
  - **And When**: I press enter
  - **Then**: I should hear that an action has occurred

**Comment by KietTruongSFDO** [comment]
**lurch: attach W-033591

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x1E0000087vOQQAY" target="_blank">W-033591</a>
