### ISSUE TITLE
Gift Entry Manager at /one/one.app does not open, redirects back to lightning home

### ISSUE THREAD

**Issue by Alexalex1432** [SalesforceFoundation/gem#262]
* **Do you want to request a *feature* or report a *bug*?**
Bug
* **What is the current behavior?**
Installing GEM in a brand new developer org does not result in being able to use GEM
* **What is the expected behavior?**
Installing GEM in a brand new developer org would allow the use of GEM
* **What is the motivation / use case for changing the behavior?**
I can't use the application
* **Acceptance Criteria**

  - **Given**: I am on https://install.salesforce.org/products/gem
  - **When**: I click install and wait for the install complete without error
  - **Then**: I should be able to use GEM

From the main lightning screen, opening the App Launcher and selecting Gift Entry Manager changes the URL to `<instance>/one/one.app` and the screen tries to load before quickly returning to the lightning home page with no error.  This developer organization has no customization in it as it was created immediately before installing GEM for this sole purpose.  I have confirmed that I received multiple emails notifying me that the package and its related packages all installed successfully.

**Comment by judisohn** [comment]
Hi @Alexalex1432 We don't provide direct support in Github. Please post in the [GEM group in the Power of Us Hub](https://powerofus.force.com/s/group/0F91E000000XbvASAS/gift-entry-manager-gem) in the future. In the meantime, the app is simply a collection of tabs and you should be able to navigate to any object or recreate the app rather than use the packaged one. If you have questions, please ask in the Power of Us Hub.

**Comment by Alexalex1432** [comment]
Hi @judisohn, I am not looking for direct support at all.  I wanted to alert you all that in a fresh environment the application does not open.

**Comment by judisohn** [comment]
Hi @Alexalex1432 Just to close the loop here... I spun up a developer org and installed GEM and I'm unable to replicate the issue you reported. Looking forward to additional information from you in the [GEM Power of Us Hub group](https://powerofus.force.com/s/group/0F91E000000XbvASAS/gift-entry-manager-gem).
